default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: password
  port: 5432
  host: localhost

development:
  <<: *default
  database: uss_rss_reader_development

test:
  <<: *default
  database: uss_rss_reader_test
